CREATE DATABASE DB1;

USE DB1;

CREATE TABLE users (
  userId INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  username VARCHAR(255) NOT NULL UNIQUE,
  emailId VARCHAR(255),
  password VARCHAR(255)
);

CREATE TABLE admins (
  adminId INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  password VARCHAR(255)
)